10 centrer la caméra sur le joueur lors de son déplacement
Yanis-Kouidri/pixel-adventurer pull request #19
Opened 2023-06-06 09:40 UTC by absolute-kinoa

2023-06-06 15:25 UTC, ThomasGRN requested changes

2023-06-06 15:25 UTC, ThomasGRN commented on src/gameengine/application/model/Camera.java
> +    }
méthode movBottom

2023-06-06 19:05 UTC, absolute-kinoa commented on src/gameengine/application/model/Camera.java
> +    }
```java
    public void moveDown() {
        coordinates.setY(getY() - Physics.NB_DEPLACEMENT_BLOCK);

    }
```

2023-06-06 19:11 UTC, absolute-kinoa commented on src/gameengine/map/model/Map.java
> +		for(int y = 0; y< Constants.MAP_ROWS-1; y++){
finalement je trouve cette version bien plus lisible

2023-06-07 06:04 UTC, ThomasGRN approved these changes

2023-06-07 06:04 UTC, merged