Feature/collision detection
Yanis-Kouidri/pixel-adventurer pull request #27
Opened 2023-06-13 00:06 UTC by ThomasGRN

2023-06-13 14:27 UTC, Grougalorasalar commented on src/gameengine/characters/model/Collisions.java
> +			if(collision == CollisionType.NONE && collisionDetected(xPositionToCheck, yPositionToCheck)) {
Space after if

2023-06-13 14:27 UTC, Grougalorasalar commented on src/gameengine/characters/model/Collisions.java
> +		for(int i = 0; i < 3; i++) {
Space after for

2023-06-13 14:27 UTC, Grougalorasalar commented on src/gameengine/characters/model/Collisions.java
> +			if(collision == CollisionType.NONE && collisionDetected(xPositionToCheck, yPositionToCheck)) {
Space after if

2023-06-13 14:27 UTC, Grougalorasalar commented on src/gameengine/characters/model/Collisions.java
> +		for(int i = 0; i < 3; i++) {
Space after for

2023-06-13 14:27 UTC, Grougalorasalar commented on src/gameengine/characters/model/Collisions.java
> +		return topSide ?
What is it ?

2023-06-13 14:27 UTC, Grougalorasalar commented on src/gameengine/characters/model/Collisions.java
> + * @author n7student
change name author

2023-06-13 14:27 UTC, Grougalorasalar commented on src/gameengine/utils/model/HitBox.java
> + * @author n7student
Change name author

2023-06-13 14:27 UTC, Grougalorasalar commented on src/gameengine/characters/model/Collisions.java
> +			switch(i) {
Switch in a for ?!

2023-06-13 14:29 UTC, Yanis-Kouidri requested changes
Fix your code before merger

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/Exceptions/NullMapException.java
> + * @author n7student
Add a real @author

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/Exceptions/NullMapException.java
> +	private static final long serialVersionUID = 1L;
Add Java doc

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/Exceptions/NullMapException.java
> + * An exception caused by the lack of setUp of the map in the class Collision
Not clear enough

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/Exceptions/UnvalidMovementDistanceException.java
> + * @author n7student
Add correct @author

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/Exceptions/UnvalidMovementDistanceException.java
> +	private static final long serialVersionUID = 1L;
add javadoc

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/Exceptions/UnvalidMovementDistanceException.java
> +	public UnvalidMovementDistanceException(float distance, float entityXpos, float entityYpos) {
Add javadoc

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/characters/model/Character.java
> +	public void moveUp() {
Add javadoc and comments

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/characters/model/Character.java
> +	public void moveRight() {
Add javadoc and comments

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/characters/model/Character.java
> +	public void moveLeft() {
Add javadoc and comments

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/characters/model/Collisions.java
> + * @author n7student
Add correct @author

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/characters/model/Entity.java
>   * @author n7student
Add correct author

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/characters/model/Collisions.java
> +	private static int getXTilePosition (boolean leftSide, HitBox hitBox) {
Make this method clearer

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/characters/model/CollisionType.java
> +enum CollisionType {
Add Javadoc

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/characters/model/Collisions.java
> +	private static int getYTilePosition (boolean topSide, HitBox hitBox) {
Make this method clearer

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/characters/model/Collisions.java
> +		for(int i = 0; i < 3; i++) {
use constant of local variable for 3

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/characters/model/Collisions.java
> +		for(int i = 0; i < 3; i++) {
Why a switch in a for loop ???

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/characters/view/EntityView.java
>  	public void paint(Graphics g) {
use a longer variable name for g

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/utils/model/Physics.java
> +    public static final float MINIMUM_BLOCK_DEPLACEMENT = 0.1f;
Add javadoc

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/utils/model/Utils.java
> +	public static int convertToPixel(float tileRatio) {
add javadoc

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/utils/model/Utils.java
> +	public static final int ceilFloatToInt(float f) {
add javadoc

2023-06-13 14:29 UTC, Yanis-Kouidri commented on src/gameengine/utils/model/Utils.java
> +	public static final int truncateFloatToInt(float f) {
add javadoc

2023-06-13 14:29 UTC, Yanis-Kouidri commented on test/gameengine/characters/model/CollisionTest.java
> +public class CollisionTest {
Add javadoc

2023-06-14 07:09 UTC, ThomasGRN commented on src/gameengine/characters/model/Collisions.java
> +			if(collision == CollisionType.NONE && collisionDetected(xPositionToCheck, yPositionToCheck)) {
Fait dans b82a7643b74fe8e4b7aeaa3f35355e17acaff2e8

2023-06-14 07:10 UTC, ThomasGRN commented on src/gameengine/characters/model/Collisions.java
> +		for(int i = 0; i < 3; i++) {
Fait dans https://github.com/Yanis-Kouidri/pixel-adventurer/commit/b82a7643b74fe8e4b7aeaa3f35355e17acaff2e8

2023-06-14 07:10 UTC, ThomasGRN commented on src/gameengine/characters/model/Collisions.java
> +			if(collision == CollisionType.NONE && collisionDetected(xPositionToCheck, yPositionToCheck)) {
Fait dans https://github.com/Yanis-Kouidri/pixel-adventurer/commit/b82a7643b74fe8e4b7aeaa3f35355e17acaff2e8

2023-06-14 07:10 UTC, ThomasGRN commented on src/gameengine/characters/model/Collisions.java
> +		for(int i = 0; i < 3; i++) {
Fait dans https://github.com/Yanis-Kouidri/pixel-adventurer/commit/b82a7643b74fe8e4b7aeaa3f35355e17acaff2e8

2023-06-14 07:17 UTC, ThomasGRN commented on src/gameengine/characters/model/Collisions.java
> +		return topSide ?
Fait dans 86ef31c2a029053fa82eb49eb3c74a3e90b90eb6

2023-06-14 07:21 UTC, ThomasGRN commented on src/gameengine/characters/model/Collisions.java
> + * @author n7student
Fait dans 6f9af7f98cac68143c721bae313a849573dcffd6

2023-06-14 07:21 UTC, ThomasGRN commented on src/gameengine/utils/model/HitBox.java
> + * @author n7student
Fait dans 6f9af7f98cac68143c721bae313a849573dcffd6

2023-06-14 07:26 UTC, ThomasGRN commented on src/gameengine/Exceptions/NullMapException.java
> + * @author n7student
Fait dans d0028c997c2f98445e5421760142d88394fc263a

2023-06-14 07:30 UTC, ThomasGRN commented on src/gameengine/Exceptions/NullMapException.java
> +	private static final long serialVersionUID = 1L;
Fait dans d0028c997c2f98445e5421760142d88394fc263a

2023-06-14 07:31 UTC, ThomasGRN commented on src/gameengine/Exceptions/UnvalidMovementDistanceException.java
> +	private static final long serialVersionUID = 1L;
Fait dans d0028c997c2f98445e5421760142d88394fc263a

2023-06-14 07:31 UTC, ThomasGRN commented on src/gameengine/Exceptions/UnvalidMovementDistanceException.java
> +	public UnvalidMovementDistanceException(float distance, float entityXpos, float entityYpos) {
Fait dans d0028c997c2f98445e5421760142d88394fc263a

2023-06-14 07:38 UTC, ThomasGRN commented on src/gameengine/characters/model/Character.java
> +	public void moveUp() {
Fait dans af5d222c155bae365a4a6db60e1ac4fa308a1c5d

2023-06-14 07:39 UTC, ThomasGRN commented on src/gameengine/characters/model/Collisions.java
> + * @author n7student
Fait dans 6f9af7f98cac68143c721bae313a849573dcffd6

2023-06-14 07:39 UTC, ThomasGRN commented on src/gameengine/characters/model/Entity.java
>   * @author n7student
Fait dans 6f9af7f98cac68143c721bae313a849573dcffd6

2023-06-14 07:40 UTC, ThomasGRN commented on src/gameengine/characters/model/Collisions.java
> +	private static int getXTilePosition (boolean leftSide, HitBox hitBox) {
Fait dans 86ef31c2a029053fa82eb49eb3c74a3e90b90eb6

2023-06-14 07:41 UTC, ThomasGRN commented on src/gameengine/characters/model/CollisionType.java
> +enum CollisionType {
Fait dans 4f852ef2b412617a15bf811d6415a6d4c922157f

2023-06-14 07:41 UTC, ThomasGRN commented on src/gameengine/characters/model/Collisions.java
> +	private static int getYTilePosition (boolean topSide, HitBox hitBox) {
Fait dans https://github.com/Yanis-Kouidri/pixel-adventurer/commit/86ef31c2a029053fa82eb49eb3c74a3e90b90eb6

2023-06-14 09:19 UTC, ThomasGRN commented on src/gameengine/utils/model/Physics.java
> +    public static final float MINIMUM_BLOCK_DEPLACEMENT = 0.1f;
Fait dans a0d4bb2ae2392a4d226031b0c0774c0fdd8cfe58

2023-06-14 09:19 UTC, ThomasGRN commented on src/gameengine/utils/model/Utils.java
> +	public static final int ceilFloatToInt(float f) {
Fait dans a0d4bb2ae2392a4d226031b0c0774c0fdd8cfe58

2023-06-14 09:19 UTC, ThomasGRN commented on src/gameengine/utils/model/Utils.java
> +	public static final int truncateFloatToInt(float f) {
Fait dans a0d4bb2ae2392a4d226031b0c0774c0fdd8cfe58

2023-06-14 09:31 UTC, Grougalorasalar approved these changes

2023-06-14 09:33 UTC, Yanis-Kouidri approved these changes
G pa lu

2023-06-14 13:36 UTC, merged