1 fenêtre de lapplication rebase
Yanis-Kouidri/pixel-adventurer pull request #6
Opened 2023-05-30 09:22 UTC by absolute-kinoa

both fenetre de l'application US + fenetre du menu

2023-05-30 19:05 UTC, ThomasGRN requested changes

2023-05-30 19:05 UTC, ThomasGRN commented on src/gameengine/application/MenuPanel.java
> +						frame.add(appWindow.getB());
Du coup si tu fais hériter ton ApplicationWindow aved le JFrame tu n'aurais plus qu'a faire un : 
**appWindow.remove(this);
appWindow.add(onClickPanel)**
avec **JPanel onClickPanel** passé en paramètre soit de la fonction, soit du constructeur, ou a la rigueur en attribut

2023-05-30 19:36 UTC, absolute-kinoa commented on src/gameengine/application/ApplicationWindow.java
> +public class ApplicationWindow {
Un peu dubitatif sur le fait de faire hériter ApplicationWindow par JFrame étant donné que le fonctionnement du JFrame n'est pas modifié, ça me parait plus logique de le laisser en tant qu'attribut

2023-05-30 19:51 UTC, ThomasGRN commented on src/gameengine/application/MenuPanel.java
> +						frame.add(appWindow.getB());
AppWindow appWindow
...
appWindow.frame.remove(this)
appWindow.frame.add(panel)

2023-05-31 12:28 UTC, absolute-kinoa commented on src/gameengine/application/ApplicationWindow.java
> +	private static JPanel b;
```java
public class PixelAdventure {

    private GamePanel gamePanel; // the view that need to be displayed on the window
    private MenuPanel menuPanel;
    private PanelMediator panelMediator;

    /**
     * a constructor.
     */
    public PixelAdventure() {
        panelMediator = new PanelMediator();
        gamePanel = new GamePanel(panelMediator);
        menuPanel = new MenuPanel(panelMediator);
        ApplicationWindow.createInstance(menuPanel); // and we add it to the window
    }

}
```
Découplage entre les custom panels et l'appWindow

2023-05-31 12:30 UTC, absolute-kinoa commented on src/gameengine/application/MenuPanel.java
> +        	PlayBtn.setForeground(Color.BLUE); // Set text color
```java
	public class MenuButton extends JButton {
		MenuButton(String text) {
			super(text);
			setFont(new Font("Arial", Font.BOLD, 16)); // Set font
		}

		MenuButton(String text, Color c) {
			super(text);
			setFont(new Font("Arial", Font.BOLD, 16)); // Set font
			setForeground(c); // Set text color

		}
	}
}

```
nouvelle pour les bouttons

2023-05-31 12:32 UTC, absolute-kinoa commented on src/gameengine/application/MenuPanel.java
> +						frame.add(appWindow.getB());
```java

public class PanelMediator {
    private GamePanel gamePanel;
    private MenuPanel menuPanel;

    public void setGamePanel(GamePanel gamePanel) {
        this.gamePanel = gamePanel;
    }

    public void setMenuPanel(MenuPanel menuPanel) {
        this.menuPanel = menuPanel;
    }

    public GamePanel getGamePanel() {
        return (gamePanel);
    }

    public MenuPanel getMenuPanel() {
        return (menuPanel);
    }

}
```
Mediateur qui sera appelé pour les changements de panel (devra p-e être refactor en EventDispatcher et utiliser des events pour gérer ça)

```java
		public void actionPerformed(ActionEvent e) {
			JFrame frame = aW.getFrame();
			JButton o = (JButton) e.getSource();
			String name = o.getActionCommand();

			if (name == "PLAY") {
				try {
					frame.remove(MenuPanel.this);
					frame.add(pm.getGamePanel());
				} catch (NullPointerException exception) {
					System.out.print(exception.getMessage());
				}
			} //...
	}
```

2023-05-31 13:13 UTC, merged